-- create_products_table.sql
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text,
  price numeric(10,2) not null default 0,
  images text[] default array[]::text[],
  available boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_products_updated_at
before update on public.products
for each row execute procedure public.set_updated_at();
